name: "\U0001F41B Bug Report"
title: "\U0001F41B [Bug]: "
description: Create a bug report to help us fix it.
labels: ["🐛 Bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and detailed description of what the bug is."
      placeholder: "Explain your problem clearly and in detail."
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      description: "Steps to reproduce the behavior and what should be observed in the end."
      placeholder: "Tell us step by step how we can replicate your problem and what we should see in the end."
      value: |
        Steps to reproduce the behavior:
        1. Go to '....'
        2. Click on '....'
        3. Do '....'
        4. See '....'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and detailed description of what you think should happen."
      placeholder: "Tell us what Optical should normally do."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Optical Version"
      description: "Some bugs may be fixed in future Optical releases, so we have to know your Optical version."
      placeholder: "Write your Optical version. (v0.2.0, v0.3.0, etc.)"
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: "Code Snippet (optional)"
      description: "For some issues, we need to know some parts of your code."
      placeholder: "Share a code snippet that you think is related to the issue."
      render: go

  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist:"
      description: "By submitting this issue, you confirm that:"
      options:
        - label: "I agree to follow Optical's [Code of Conduct](https://github.com/TuhinBar/optical/blob/main/docs/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have checked for existing issues that describe my problem prior to opening this one."
          required: true
        - label: "I understand that improperly formatted bug reports may be closed without explanation."
          required: true
