name: "📝 Feature Proposal"
title: "📝 [Proposal]: "
description: Propose a feature or improvement for Optical.
labels: ["📝 Proposal", "✏️ Feature"]

body:
  - type: markdown

  - type: textarea
    id: description
    attributes:
      label: "Feature Proposal Description"
      description: "A clear and detailed description of the feature you are proposing for Optical. How should it work, and what methods would it involve?"
      placeholder: "Describe your feature proposal clearly and in detail, including API endpoints and methods."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: "Feature Examples"
      description: "Provide concrete examples and code snippets to illustrate how the proposed feature should function."
      placeholder: "Share code snippets that exemplify the proposed feature and its usage."
      render: go
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist:"
      description: "By submitting this issue, you confirm that:"
      options:
        - label: "I agree to follow Optical's [Code of Conduct](https://github.com/TuhinBar/optical/blob/main/docs/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have searched for existing issues that describe my proposal before opening this one."
          required: true
        - label: "I understand that a proposal that does not meet these guidelines may be closed without explanation."
          required: true
